config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 root 'varieties#index'
 get 'varieties/about' => 'varieties#about'
 get 'varieties/rank' => 'varieties#rank'
 resources :varieties do
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :variety
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :variety
  belongs_to :user
  validates_uniqueness_of :variety_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   has_many :varieties, dependent: :destroy
   has_many :likes, dependent: :destroy
   has_many :liked_varieties, through: :likes, source: :variety
   has_many :comments, dependent: :destroy

   validates :name, presence: true #追記
   validates :profile, length: { maximum: 200 } #追記

   def already_liked?(variety)
    self.likes.exists?(variety_id: variety.id)
   end

  end

app/models/variety.rb
class Variety < ApplicationRecord
    belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
    mount_uploader :image, ImageUploader
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      # サインアップ時にnameのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      # アカウント編集の時にnameとprofileのストロングパラメータを追加
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
  
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      variety = Variety.find(params[:variety_id])
      comment = variety.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
  end
  

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(variety_id: params[:variety_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(variety_id: params[:variety_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/controllers/varieties_controller.rb
class VarietiesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]  
    def about
    end

    def rank
      @rank_varieties =  Variety.find(Like.group(:variety_id).order('count(variety_id) desc').limit(3).pluck(:variety_id))
    end

    def index
       @varieties = Variety.all.order(id: "DESC")
       
    end

    def new
      @variety = Variety.new
    end

    def create
        variety = Variety.new(variety_params)
        variety.user_id = current_user.id
      if variety.save!
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end

    def show
       @variety = Variety.find(params[:id])
       @comments = @variety.comments
        @comment = Comment.new
    end

    def edit
       @variety = Variety.find(params[:id])
    end

    def update
        variety = Variety.find(params[:id])
     if variety.update(variety_params)
        redirect_to :action => "index", :id => variety.id
      else
        redirect_to :action => "new"
    end
   end


   def destroy
     variety = Variety.find(params[:id])
     variety.destroy
     redirect_to action: :index
   end

    private
    def variety_params
      params.require(:variety).permit(:title, :about, :date, :cast, :image, :rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/varieties_helper.rb
module VarietiesHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end 
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>Likeflower</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <link rel="stylesheet" href="./stylesheets/index.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  </head>

  <body>
      <header>
      <h1>likeflower</h1>
      <div class="header-list">
      <ul>
      　　<% if user_signed_in? %>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"iro" %></li>
          <% else %>
          <li><%= link_to "新規登録", new_user_registration_path , class:"iro"%></li>
          <li><%= link_to "ログイン", new_user_session_path, class:"iro" %></li>
          <% end %>
      
        <% if user_signed_in? %>
          <%= link_to "マイページへ", user_path(current_user.id), class:"iro" %>　
        <% end %>

        <li><%= link_to "ランキング",varieties_rank_path, class:"iro" %></li>
        <li><%= link_to "ホーム", varieties_path, class:"iro" %></li>
        <li><%= link_to "新規投稿",new_variety_path, class:"iro" %></li>
        <li><%= link_to "このサイトについて",varieties_about_path, class:"iro" %></li>
      </ul>
      </div>
      </header>
       <main>
       <div class="mainnoiro">
       </div>
       
      <%= yield %>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
     </main>
    <footer>
       <small>© 2020 大内田祐太朗</small>  
    </footer>
  </body>
  
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="kubochan">
<div class="toukoup">
</div>
</div>
<div class="maipagei">
<i>MY PAGE</i>
</div>
<div class="maipage">
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
</div>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.varieties.each do |t| %>
  <div class="card2" style="width: 18rem;">
         <div class="card-title">
          <%= t.title %>
         </div>
         <a href="/users/<%= t.user.id %>"><%= t.user.name %></a><br>
         <%= image_tag t.image_url, size: "250x200" if t.image? %>      
          <div id="star-rate-<%= t.id %>"></div>
          <script>
          $('#star-rate-<%= t.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= t.rate%>,
          });
          </script> 
        <div class= "tekitou" style="width: 18rem;">
          <%= t.about %>
        </div>
          <%= t.date %><br>
          <%= t.cast %><br>
          <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                    <%= link_to variety_like_path(id: t.id, variety_id: t.id), method: :delete do %>
                      <i class="fas fa-heart"></i><%= t.likes.count %>
                    <% end %>
                <% else %>
                  <%= link_to variety_likes_path(id: t.id, variety_id: t.id), method: :post do %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                 <% end %>
                <% end %>
      <% else %>
          <p>いいねの数 = </p><%= t.likes.count %>
          <i class="far fa-heart"></i>
      <% end %>
          <%= t.created_at %></br>
          
         <div class="right">
              <%= link_to "詳細へ", variety_path(t.id) %>
            <% if user_signed_in? && current_user.id == t.user_id %>  
              <%= link_to "編集する", edit_variety_path(t.id) %>
            <% end %> 
         </div>
    </div>
  
    </div>
<% end %>



<!-- ここまで-->

app/views/varieties/about.html.erb
<%= stylesheet_link_tag 'about', :media => "all" %>

  <body>
   <!--   First block Start   -->
  <section id="first-block">
    <div class="title-container">
      <h1>バラエティが好き</h1>
      <h3> このサイトは自分が好きなバラエティ番組を共有するサイトです｡</h3>
    </div>
      </section>
  <!--   First block End   -->
　<!--   Second block Start   -->
<section id="second-block">
    <p class="tukaikata">
      使用方法
    </p>
  </section>
<section id="third-block">
    <p class="info-title">
    </p>
    <div class="about-container">
      <p class="info-text">
        <b>①アカウントを作成しましょう</b>
      </p>

      <p class="info-text">
        <b>②プロフィールを編集しましょう</b>
      </p>

      <p class="info-text">
        <b>③見た番組のレビューを書き込む</b>
      </p>

      <p class="info-text">
        <b>④10段階で評価する</b>
      </p>

      <p class="info-text">
        <b>⑤他の人の投稿に反応しよう</b>
      </p>

    </div>
  </section>
  <!--   Second block End   -->
   <!--   Third block Start   -->
  <section id="forth-block">
    <p class="events-title">
      LIKEFLOWER とは
    </p>
    <div class="event-container">
      <div class="event">
        <p class="event-name">
          <span>もっとテレビバラエテイに需要を増やしたい
          </span>
          <br>
          今日動画配信サイトの普及によりテレビを見る若者が<br>
          減ってきていると思います。しかし世の中には面白いのに<br>
          まだ見つかってない番組も多く存在します。<br>
          このサイトはそんな番組も注目されるように<br>
          口コミを共有できるサイトでありたいと思っています。<br>
          様々な意見をご投稿ください。<br>
          また｢MY PAGE｣に自己紹介を載せることができます。<br>
          好みのｼﾞｬﾝﾙや好きなMC､アナウンサー､放送局など<br>
          好きなことを沢山紹介しましょう！<br>
        </p>
      </div>
    </div>
  </section>
  <!--   Third block End   -->
  <!--  コンテンツはここまで  -->
  
  </body>
</html>

app/views/varieties/edit.html.erb
<%= form_for @variety do |f| %>
    <div class="container">
      <div class="container2">
          <div class="field">
            <%= f.label :title %>
            <%= f.text_field :title, :size => "60x3" %>
          </div>

          <div class="field">
            <%= f.label :about %>
            <%= f.text_field :about, :size => "60x13" %>
          </div>
      </div>
      <div class="container2">
        <div class="field">
        <%= f.select :date,
        [["月曜日","月曜日"],
          ["火曜日","火曜日"],
          ["水曜日","水曜日"],
          ["木曜日","木曜日"],
          ["金曜日","金曜日"],
          ["土曜日","土曜日"],
          ["日曜日","日曜日"]], include_blank: "選択してください" %>
       </div>

      <div class="field">
      <%= f.label :cast %>
      <%= f.text_field :cast, :size => "60x4" %>
      </div>

      <%= f.file_field :image %><br>
      <%= f.submit "編集する" %><br>
    </div>

  <% end %>

app/views/varieties/index.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

       <section id="index-block">
    <div class="ichiran">
      投稿一覧
    </div>
      </section>
  <% @varieties.each do |t| %>
    <div class="card2" style="width: 18rem;">
           <% if t.image? %>
           <img src= "<%= t.image_url %>" size: "278x200" class="card-img-top" >
          <% else %>
          <%= image_tag "noimages.jpg", class:"card-img-top" %>
          <% end %>
         <div class="card-title">  
         <%= t.title %>
         </div>
          <a href="/users/<%= t.user.id %>"><%= t.user.name %></a><br>    
          <div id="star-rate-<%= t.id %>"></div>
          <script>
          $('#star-rate-<%= t.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= t.rate%>,
          });
          </script> 
          <%= t.date %><br>
          <i class="fas fa-user-alt"></i>キャスト:<%= t.cast %><br>
      <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                    <%= link_to variety_like_path(id: t.id, variety_id: t.id), method: :delete do %>
                      <i class="fas fa-heart"></i><%= t.likes.count %>
                    <% end %>
                <% else %>
                  <%= link_to variety_likes_path(id: t.id, variety_id: t.id), method: :post do %>
                    <i class="fas fa-heart"></i><%= t.likes.count %>
                 <% end %>
                <% end %>
      <% else %>
          <p>いいねの数 = </p><%= t.likes.count %>
          <i class="far fa-heart"></i>
      <% end %>
          <%= t.created_at %></br>
          
         <div class="right">
              <%= link_to "詳細へ", variety_path(t.id) %>
            <% if user_signed_in? && current_user.id == t.user_id %>  
              <%= link_to "編集する", edit_variety_path(t.id) %>
            <% end %> 
         </div>
    </div>
  <% end %>




<% if user_signed_in? %>
     
       <% else %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
       <% end %>
      
 

app/views/varieties/new.html.erb
<div class="kubochan">
<div class="teletele888">
</div>
</div>
<h3>新規投稿</h3>
<%= form_for @variety do |f| %>
  <div class="container">
    <div class="container2">
        <div class="field">
        <%= f.label :番組名 %>
        <%= f.text_field :title, :size => "60x3" %>
        </div>
        <div class="form-group " id="star">
        <%= f.label :rate,'総合評価', class:'col-md-3 col-form- label' %>
        <%= f.hidden_field :rate, id: :review_star %>
        </div>
        <!-- 評価javascript -->
        <script>
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'variety[rate]',
          half: true,
        });
        </script>  


        <div class="field">
        <%= f.label :番組内容 %>
        <%= f.text_field :about, :size => "60x13" %>
        </div>
      </div>
      <div class="container2">
      <div class="field">
      <%= f.label :放送日 %>
      <%= f.select :date,
      [["月曜日","月曜日放送中!!"],
        ["火曜日","火曜日放送中!!"],
        ["水曜日","水曜日放送中!!"],
        ["木曜日","木曜日放送中!!"],
        ["金曜日","金曜日放送中!!"],
        ["土曜日","土曜日放送中!!"],
        ["日曜日","日曜日放送中!!"]], include_blank: "選択してください" %>
      </div>

      <div class="field">
      <%= f.label :cast %>
      <%= f.text_field :cast, :size => "60x4" %>
      </div>

      <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
        <%= f.submit "PUSH", class:"btn-flat-simple col-md-10" %>  
   </div>
   </div>
<% end %>
<%= link_to "バラエティ一覧に戻る", varieties_path %>

app/views/varieties/rank.html.erb
<div class="hyoushou">
</div>
<h2>ランキング</h2>
  <% @rank_varieties.each.with_index(1) do |t,i| %>
    <div class="card2" style="width: 18rem;">
    <i class="fas fa-crown"></i>第<%= i %>位
    <% if t.image? %>
    <img src= "<%= t.image_url %>" size: "278x200" class="card-img-top" >
   <% else %>
   <%= image_tag "noimages.jpg", class:"card-img-top" %>
   <% end %>
    <div class="card-title">  
     <%= t.title %>
    </div>
    <%= t.about %>
     <a href="/users/<%= t.user.id %>"><%= t.user.name %></a><br>    
     <%= t.date %><br>
     <i class="fas fa-user-alt"></i>キャスト:<%= t.cast %><br>
    </div>
  <% end %>

app/views/varieties/show.html.erb
<h3>番組詳細</h3>
<div class="matsutai">
<%= image_tag @variety.image_url, size: "450x300" if @variety.image? %>
</div>
  <div class="card-title">
  <%= @variety.title %>
  </div>
  <div class="tekitou2"><%= @variety.about %>
  </div>
    <div class="tekitou3">
  <p>放送日:<%= @variety.date %></p>
  <i class="fas fa-user-alt"></i><p><%= @variety.cast %></p>
   <% if user_signed_in? %>
   <% if current_user.already_liked?(@variety) %>
       <%= button_to variety_like_path(@variety), method: :delete do %>
        <i class="fas fa-heart"></i><%= @variety.likes.count %>
    </div>
       <% end %>
    <% else %>
       <%= button_to variety_likes_path(@variety), method: :post do %>
        <i class="far fa-heart"></i><%= @variety.likes.count %>
       <% end %>
      <% end %>
    <% else %>
   <i class="far fa-heart"></i><%= @variety.likes.count %>
   <% end %>
   </div>

   <div class="comment-wrapper">
   <div class="toukoutitle">
    コメント一覧
    </div>
    <% @comments.each do |c| %>
      <div class="haikei22">
        <%= c.user.email unless c.user.blank? %>
        <br>
        <%= c.content %>
      </div>
        <br>
   <% end %>
 
   <% if user_signed_in? %>
     <%= form_with(model: [@variety, @comment], local: true) do |f| %>
      <div class="field">
      <%= f.text_area :content, :size => "105x2" %>
      </div>
      <div class="contentbutton">
       <%= button_tag type: "submit" do %>
         <i class="far fa-comments"></i> コメントする   
         </div>
       <% end %>
     <% end %>
   <% end %>


<%= link_to "variety一覧に戻る", varieties_path %>